name: Deploy Gazette to IONOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: access-5020341214.webspace-host.com
          port: 22
          username: ${{ secrets.IONOS_FTP_USERNAME }}
          password: ${{ secrets.IONOS_FTP_PASSWORD }}
          local_path: ./index.html
          remote_path: /Gazette/httpdocs/
          sftp_only: true
